qualquerCoisa = input('Digite qualquer coisa no teclado: ')
print('O tipo primitivo desse valor é {}'.format(type(qualquerCoisa)))
print('Só tem espaços? {}'.format(qualquerCoisa.isspace()))
print('É um número? {}' .format(qualquerCoisa.isnumeric()))
print('É alfabético? {}'.format(qualquerCoisa.isalpha()))
print('É alfanúmerico? {}'.format(qualquerCoisa.isalnum()))
print('Éstá em maiúsculas? {}'.format(qualquerCoisa.isupper()))
print('Está em minúsculas? {}'.format(qualquerCoisa.islower()))
print('Está capitalizada? {}'.format(qualquerCoisa.istitle()))