print('-' * 15)
print('|',end='')
print(' CALCULADORA ',end='')
print('|')
print('-' * 15)
print('|             |')
print('-' * 15)
print('| [7] [8] [9] |')
print('| [4] [5] [6] |')
print('| [1] [2] [3] |')
print('-' * 15)